# Generated by Django 4.2.9 on 2024-10-29 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0002_userprofile_and_more'),
        ('Avis', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avis',
            old_name='created_at',
            new_name='date',
        ),
        migrations.RemoveField(
            model_name='avis',
            name='comment',
        ),
        migrations.RemoveField(
            model_name='avis',
            name='experience',
        ),
        migrations.AddField(
            model_name='avis',
            name='experience_name',
            field=models.CharField(default='Experience sans nom', max_length=200),
        ),
        migrations.AddField(
            model_name='avis',
            name='feedback',
            field=models.TextField(default=0),
        ),
        migrations.AlterField(
            model_name='avis',
            name='rating',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='avis',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='preferences.userprofile'),
        ),
    ]
