# Generated by Django 4.2.9 on 2024-12-06 16:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('voyages', '0001_initial'),
        ('Avis', '0004_remove_avis_commentaire_remove_avis_note_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avis',
            name='experience_name',
        ),
        migrations.RemoveField(
            model_name='avis',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='avis',
            name='rating',
        ),
        migrations.AddField(
            model_name='avis',
            name='commentaire',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='avis',
            name='note',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=0),
        ),
        migrations.AddField(
            model_name='avis',
            name='voyage',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='avis', to='voyages.voyage'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='avis',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
