# Generated by Django 4.2.9 on 2024-12-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyages', '0002_voyage_continent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voyage',
            name='continent',
            field=models.CharField(default='Non spécifié', max_length=100),
        ),
    ]
