# Generated by Django 4.2.9 on 2024-12-07 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voyages', '0003_alter_voyage_continent'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyage',
            name='activities',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='voyage',
            name='duration',
            field=models.CharField(default='Non spécifié', max_length=50),
        ),
        migrations.AddField(
            model_name='voyage',
            name='travel_mode',
            field=models.CharField(default='Non spécifié', max_length=20),
        ),
        migrations.AddField(
            model_name='voyage',
            name='travel_type',
            field=models.CharField(default='Non spécifié', max_length=50),
        ),
    ]
