# Generated by Django 4.2.9 on 2024-12-07 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voyages', '0004_voyage_activities_voyage_duration_voyage_travel_mode_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='voyage',
            name='activities',
        ),
    ]
