# Generated by Django 4.2.9 on 2024-12-07 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('experiences', '0002_userreaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='experience',
            name='like_count',
            field=models.IntegerField(default=0),
        ),
    ]
