# Generated by Django 4.2.9 on 2024-12-07 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0002_userprofile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preference',
            name='preference_type',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='value',
        ),
        migrations.AddField(
            model_name='preference',
            name='activities',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='preference',
            name='budget',
            field=models.CharField(default='Non spécifié', max_length=20),
        ),
        migrations.AddField(
            model_name='preference',
            name='duration',
            field=models.CharField(default='Non spécifié', max_length=50),
        ),
        migrations.AddField(
            model_name='preference',
            name='preferred_destination',
            field=models.CharField(default='Non spécifié', max_length=100),
        ),
        migrations.AddField(
            model_name='preference',
            name='preferred_period',
            field=models.CharField(default='Non spécifié', max_length=20),
        ),
        migrations.AddField(
            model_name='preference',
            name='travel_mode',
            field=models.CharField(default='Non spécifié', max_length=20),
        ),
        migrations.AddField(
            model_name='preference',
            name='travel_type',
            field=models.CharField(default='Non spécifié', max_length=50),
        ),
    ]
