# Generated by Django 4.2.9 on 2024-12-08 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preferences', '0005_alter_preference_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preference',
            name='budget',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
